source "https://rubygems.org"

ruby "3.2.2"
gem "rails", "~> 7.1.3", ">= 7.1.3.2"

# postgre
gem "pg", "~> 1.1"

gem "puma", ">= 5.0"

gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

# 画像加工
gem "mini_magick"
gem "image_processing", "~> 1.2"

# CORS対策
gem "rack-cors"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "pry-byebug"
  gem 'annotate' # モデルのスキーマを表示する
end

group :production do
  # 画像保存のストレージサービス
  gem "aws-sdk-s3", require: false
end

# .envを使うため
gem 'dotenv-rails'
# フロントとバックを分けているので同じサイト判定させるためのgem
gem 'rails_same_site_cookie'
# 認証
gem "devise"
# トークンの方はRails7に対応していないので、githubから取得
gem 'devise_token_auth', '>= 1.2.0', git: "https://github.com/lynndylanhurley/devise_token_auth"
# 多言語用
gem 'devise-i18n'
# OAuth2.0用
gem 'omniauth'
# Googleの認証用
gem 'omniauth-google-oauth2'
# Discordの認証用
gem 'omniauth-discord'
# CSRF対策用
gem "omniauth-rails_csrf_protection"
# JSONのシリアライザー
gem 'jsonapi-serializer'
